### ISSUE TITLE
Finish setting up this repository

### ISSUE THREAD

**Issue by ixdy** [kubernetes-sigs/boskos#3]
A number of tasks remain. In no particular order:
- [x] import code from kubernetes/test-infra (#1)
- [x] fix build (#2)
- [x] get CI set up on Prow (https://github.com/kubernetes/test-infra/pull/17647)
  - [x] build and unit testing using standard Go tooling (instead of Bazel), e.g. using `gotestsum` for junit output (#4)
  - [x] verification scripts (go vet, other linters, and relevant verify- scripts from `kubernetes/repo-infra`) (#4)
  - [x] image build (#8) and pushes (https://github.com/kubernetes/test-infra/pull/17718), maybe initially using Bazel, but eventually just using Docker
- [x] import issues from `kubernetes/test-infra`
- [x] fix any dependencies in `kubernetes/test-infra` (e.g. the GCP janitor script, Prow auto-bumper, etc) (https://github.com/kubernetes/test-infra/pull/17721)
- [x] update any easily-discoverable golang dependencies in other repos
  - [x] https://github.com/openshift/ci-tools (https://github.com/openshift/ci-tools/pull/885)
  - [x] https://github.com/knative/pkg (https://github.com/knative/pkg/pull/1378)
  - [x] https://github.com/istio/test-infra (https://github.com/istio/test-infra/pull/2691)
- [x] remove `boskos/` directory from `kubernetes/test-infra` (https://github.com/kubernetes/test-infra/pull/17723)
- [x] [announce to sig-testing that boskos has moved](https://groups.google.com/g/kubernetes-sig-testing/c/KfjlilCF9cA/m/TYBwWII1AQAJ)
